variables:
  buildConfiguration: 'Release'
  testsRunFramework: 'net45'

jobs:
- job: BuildAndRunTests
  displayName: Build and run tests
  pool:
    name: Hosted VS2017
  steps:
  - task: DotNetCoreCLI@2
    displayName: Build solution
    inputs:
      command: build
      projects: '**\*.sln'
      arguments: -c $(buildConfiguration) /p:RunCodeAnalysis=true /warnaserror
  - task: DotNetCoreCLI@2
    displayName: Run tests
    timeoutInMinutes: 30
    continueOnError: true
    inputs:
      command: test
      projects: '**\*.Tests.csproj'
      arguments: -f $(testsRunFramework) --no-build
  - task: PublishPipelineArtifact@0
    displayName: Publish test results
    inputs:
      artifactName: Test results
      targetPath: src/Atata.KendoUI.Tests/bin/$(buildConfiguration)/$(testsRunFramework)/Logs