queue:
  name: Hosted VS2017
  demands: vstest
  
variables:
  buildConfiguration: 'Release'
  
steps:
- task: DotNetCoreCLI@2
  displayName: 'Build solution'
  inputs:
    projects: '**\*.sln'
    arguments: '-c $(buildConfiguration) /p:RunCodeAnalysis=true /warnaserror'

- task: VSTest@2
  displayName: 'Run tests'
  inputs:
    testAssemblyVer2: |
      **\*.Tests*.dll
      !**\obj\**

- task: PublishPipelineArtifact@0
  displayName: 'Publish test results'
  inputs:
    artifactName: 'Test results'
    targetPath: src/Atata.KendoUI.Tests/bin/$(buildConfiguration)/net45/Logs
  condition: succeededOrFailed()